# Admin user configuration
ssh_port: ENC[AES256_GCM,data:BxbaTGA=,iv:jkSVwvvS0nQ31HTR/9e/AL3Fb1qB2B170IbuveOJqHk=,tag:Mg8imgnCkwdBhrxes2K9cQ==,type:int]
admin_username: ENC[AES256_GCM,data:hUhBil+OHQ==,iv:sS/eBIq4VyTKeLr7FpkHVvC/v08zQUnGIScmTGKJ4uc=,tag:nLU+h2ZS5D/1gakuczHO1A==,type:str]
# Should be defined in vault or group_vars
admin_ssh_public_keys:
    - ENC[AES256_GCM,data:GLv6TLyqMcmyhHVPWhNP1KSlBZI2fLvWRHPH1Sg/XJAOmqHy0ACuC1x5rMMRhsAGE2aH91bPiOmFt3+RYnxyo2rLA+qxV6PdR+I2Z/4IQVkqn0ninog2MmtH1CPfsc2V8MDPe446UA==,iv:dkxiQblJWeFnHN11gpu9qdYiTJZEXC+0OtpeCBJ0OHs=,tag:vQIRjcb5dVHxBEV2fgJPGg==,type:str]
    - ENC[AES256_GCM,data:iAmBH/I9ClBqZtL2I0H1TqMxPorKl7ywXmTw1zDEkbkyC4k7II1RwPCiF4GrH5K/mtVOB2V1k234iG/z48vd2fz6h7lGLSUqGsSA4aGnar0yhBUw2YMDXYCEwJeZaR0iPZbNXXIQpw==,iv:qaSW0a547EIuhkJrcOsmgvfHsKf9ZiY6PDszsBShy0E=,tag:2RiSRg8pdjMsvuZVu35v6A==,type:str]
# Ansible user SSH keys
# Should be defined in vault or group_vars
ansible_ssh_public_keys:
    - ENC[AES256_GCM,data:TIdbMIBND6lJB8yMKOjoCudIhvCNrxIe+r6DlW4GshJ6WRqz098AaNb73j0u5pFq2FRlGtcx0GcgBNCOkZsHonbjMt+BIPbyScvDhPNOWgXGg37LKREUdmCGWNdiq+nqVUJL+0n5GQ==,iv:Ikmze//JjFldkdYYETRp/R/zb3MvuqJyKeZe9AofUNg=,tag:PEmmdDmIEzYOT6oG/rVgWQ==,type:str]
    - ENC[AES256_GCM,data:UfoGOf99qWKmL8zONsPsMgj+iT4HsVxLxiQysC5wK2BerXjK1RZFGupRyAyG7GvY/4bROFMeMK2fX969X3T+P8xQQ/Lk3nD8Tlhi+3GbmZUIFDF/7MyQ7EmB9uwWNYeuK1soQUw0kQ==,iv:82Mx5qpuxUap2hV11TZ990hF1neFwDP7lfkMs3DM1z0=,tag:ytVXinx1GQ9ReC4+aCPMXQ==,type:str]
ansible_github_creds:
    username: ENC[AES256_GCM,data:6nOMquJ7Is4=,iv:XUBU/JUrd8ikWLQBz0lT8IHNzcPn3CNeywwkCWZrKIQ=,tag:9ett1esRJohJAqCRcfG+tA==,type:str]
    password: ENC[AES256_GCM,data:/wIM4Rk2KAsOnIFcRenRzpHbytcy4z3qoPANfuUnHIOwiqfTGlM+LDd4Gvl1YEJigQZMRWTM2Dz1tWke1BN0Av2eLc5kAGxEW/V9kRVhUUo1Eu37rnzyRYcThvyY,iv:+Fio+Ou2lNKz3sxXvtTMtPMziFHjY5bsjMKIb0F/N0s=,tag:ZYoHPTosYTwoQlDtAQmFxw==,type:str]
sops:
    age:
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIP0YSN9LnJN09PNG0cBa3quStOaSlv9Hyp2+PQDL0MD1 gbwebdev@github/60953839
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNTK1A1dyBuNVk0
            eDhWZzY2RzdBMDIyY1VXd0w1LzBueEYzRm1PWkJlekJLZ3cvTGpBClRqOVhFZ0VL
            bGxSRWd4bHE4OEdvbXBJZEMrQ25NZGFIWGRHTTk0TG56Rm8KLS0tIG14MTR2Zmtz
            QmkvRXVzMHdOTlVIZXlvYnMzZjUzM1NlNCtxVXJpYUdBRmcKXGW9RGr2LymAvC4E
            gN81dxP2/cW/6AuthMyjN44lBMk2zmEFAzB1JiY5XaUKceV9T+DAY7UWqwp2aEnQ
            AkyGBQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMENiGNM4RyfklfW9ZlJix9zYbifWyTVaRYY08HbZ2wL gbwebdev@github/62232576
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDVMYVFkQSBkZW9z
            ZWU0Tk1TbXRkbHhRZ3JsajhLbWdSWVRhdkVmODZhN1oxK3FTNFY0ClF6YjNBTzRO
            c2VtV3QwVnZ2eVlOTGZGNE5yc3BQR1BsZ0Z1UmxwVHZrM2sKLS0tIHJ0alRmb0Yz
            TW4ycTE1OFRQQ2hmU3BPTHJTU0dqbVcwU3BRRTNvZWtSU0EK9xLkVi7XvONqTmAn
            LnK9xDR5sJaOF1GkB9+m/WuLzSNg9kBX7h43B4uXXEcbrt/ELP8y10IbjWvHru7P
            CDcA+w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFXZ9OLEwcxzuMPXYJyhNBDnawJvXCwQZLm28kZ0flxJ guillaume@LP-Guillaume
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IHJsYTgzQSA4azlH
            MXIwcnN4eTdtWTgvcHlVUXlpOUVQY0RjdkIrL1RKQ0JQeVZhN2xnCjM0aW9VOWlQ
            OGdIZkxoY0wxZHdzSERFS0UvTVgrMEdKQ3dCcUZZM0NQWUkKLS0tIEpYcXdUNzIw
            VUxCSG9DWUFxTUZYNmRyYW5jSGRPenExanNKS3MvV3kwalkKbH7UDLF02ZPqAgkt
            SHPSG25aR4ssALSx1ss38/oYbDYysohA53ub6eG71qzgvSMTK1a2y0xFO/E+65ya
            ES1RJw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILO9kGZmoqzzsSi/l2rbS8uGtPEFD3P5xd5TVi5ejtnj guillaume@PC-Guillaume
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IEt0VDNHZyA0NlFo
            YmQ3bTU4ei96TENmV2FyZlBFVnhpWkMrYWNNVCtLOHp2SUFQN0g0CitZZE5yU01J
            ekxURGY4eHR1MW1ySEFkMFQvcWt6SlpzSmNyWEZUMlAyMFEKLS0tIFo2Z3l4OHFk
            bm1JSXhCb0Jwd2x6U3gzaDZUQmNkVHltcWhNL1FPMTdHR0UKOf/G4PcjBhRKxKHJ
            AxV26Wl3QrC+BGTN39WkaU9btwVqAmuwc07AK8FWhDwCeELWL7G2bAk1RWXzuSQP
            pwpXDA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-09T17:38:50Z"
    mac: ENC[AES256_GCM,data:2Mot1KiXBViUlRDM4YZ0e3Me485gjRPp6ZDdUpejDeaQFKpt2BDsMNtARj0oum6HFOym/7Dh0Ycuo0uMtc8f846Z9TbbA/omvvq3PZbC2k2rzSSXf5pVXPNk3pjK4f73b/JOeWobZMwaoiNY3sgDiHnwca/XahYfozS8G2O+NFE=,iv:l1eo06GtHT4Anp1XGO0G1tPfkHNHhXUzGAAbaMyxpyk=,tag:nOUQdSQ1VJoaGoesc9B2SA==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.11.0
